Was sind die Kommunikationskanäle für die Übungen?
Ich habe ein Problem oder eine Frage, welche zu komplex ist um sie textuell als Ticket zu beschreiben. Wo bekomme ich einen Besprechungstermin?
Wie kommuniziert ihr mit uns?
Ich verstehe etwas an der Aufgabenstellung / dem vorgegebenen Code (falls vorhanden) / den vorgegebenen Kommentaren (falls vorhanden) nicht.
Ich habe weniger als 100% im Servertest und beim besten Willen keine Idee woran es liegen könnte. Wo bekomme ich Hilfe?
Ich hab das FAQ komplett gelesen und jetzt traue ich mich nicht mehr euch was zu fragen.
